### ISSUE TITLE
Create Release/tag for the PyHEP 2022 "proceedings" on Zenodo

### ISSUE THREAD

**Issue by eduardo-rodrigues** [SengerM/the_bureaucrat#2]
Hello @SengerM, could you do that asap so that I then add your workshop contribution to the "proceedings", see https://zenodo.org/communities/pyhep2022 (example of last year: https://zenodo.org/communities/pyhep2021). Advance thanks.

**Comment by SengerM** [comment]
Dear @eduardo-rodrigues I have created the tag, sorry for the delay. Please let me know should I do something else.

**Comment by eduardo-rodrigues** [comment]
That's all I need. The rest I take care. Once done with everything I will send an email around. Many thanks.
